### ISSUE TITLE
modify BrowserModPlayer to extend MediaPlayerEntity

### ISSUE THREAD

**Issue by iptvcld** [JeffLIrion/ha-androidtv#10]
Updated to: 2af316a

But still getting

Logger: homeassistant.components.media_player
Source: components/media_player/init.py:938
Integration: Media player (documentation, issues)
First occurred: 2:22:16 AM (1 occurrences)
Last logged: 2:22:16 AM

MediaPlayerDevice is deprecated, modify BrowserModPlayer to extend MediaPlayerEntity

**Comment by JeffLIrion** [comment]
That's not related to this custom component.

**Comment by iptvcld** [comment]
Thanks
