### ISSUE TITLE
Philips Android TV HDMI support

### ISSUE THREAD

**Issue by Skons** [JeffLIrion/ha-androidtv#6]
Hello,

I think this is the right place for this issue, please let me know if this should be reported elsewhere.

My Philips TV does not support the HDMI commands defined in the constants.py. I can only switch with the Function keys.

To switch to HDMI I use the following command:
`command: "input keyevent KEYCODE_F1"`

Though the difficult thing about these keycodes is that they account for a seemingly random available input. Which means that I switch to HDMI2 with F1 and to YPbPr with F2 and F3. HDMI 4 is available through F4 and F5 will give me my HDMI1. Which does not seem to make sense. Even the way my sources are sorted, does not correspond with this order.

So, i have the issue that i cannot switch to HDMI with the default available Keys. But it probably cannot be made predictable by handling the function keys in the code. Though i would like to help to see if we can somehow resolve this. To have it known that this issue exist is the minimum what i can do.

**Comment by JeffLIrion** [comment]
It doesn't sound like there's a solution to this other than sending `input keyevent KEYCODE_*` commands. But that doesn't seem like such a big deal, right?

**Comment by Skons** [comment]
No, it is not a big deal at all, though it would be very nice if you would not have to think about it as HA user. To have this known to the users i think it would be nice to have [this](https://www.home-assistant.io/integrations/androidtv) documentation updated.

**Comment by JeffLIrion** [comment]
You're welcome to submit a pull request to include that in the documentation.
