### ISSUE TITLE
When andriodTV is displaying the dream screensaver - missing app_id

### ISSUE THREAD

**Issue by iptvcld** [JeffLIrion/ha-androidtv#7]
When androidTV is displaying the dream screensaver - no info is shown in HA
```
adb_response: null
friendly_name: Family Room TV
supported_features: 23997
icon: mdi:television-classic
```

I have an older version of your work and it would display the app_id even when the screen saver is on.  And with that i can display the output in HA

```
volume_level: 0.4
is_volume_muted: false
app_id: Sys2023:dream}
app_name: Displaying Screensaver
source: hdmi
adb_response: null
friendly_name: Family Room TV
supported_features: 21945
icon: mdi:television-classic
```

**Comment by JeffLIrion** [comment]
This is just a custom component for testing purposes.  The library that the component uses is https://github.com/JeffLIrion/python-androidtv.  

But you can go ahead and run this using the `androidtv.adb_command` service and post the output (from the `adb_response` state attribute):

```yaml
entity_id: media_player.family_room_tv
command: "(dumpsys power | grep 'Display Power' | grep -q 'state=ON' || dumpsys power | grep -q 'mScreenOn=true') && echo -e '1\\c' || echo -e '0\\c' && dumpsys power | grep mWakefulness | grep -q Awake && echo -e '1\\c' || echo -e '0\\c' && (dumpsys audio | grep paused | grep -qv 'Buffer Queue' && echo -e '1\\c' || (dumpsys audio | grep started | grep -qv 'Buffer Queue' && echo '2\\c' || echo '0\\c')) && dumpsys power | grep Locks | grep 'size=' && CURRENT_APP=$(dumpsys window windows | grep mCurrentFocus) && CURRENT_APP=${CURRENT_APP#*{* * } && CURRENT_APP=${CURRENT_APP%%/*} && echo $CURRENT_APP && (dumpsys media_session | grep -A 100 'Sessions Stack' | grep -A 100 $CURRENT_APP | grep -m 1 'state=PlaybackState {' || echo) && dumpsys audio | grep '\\- STREAM_MUSIC:' -A 12 && ps -A | grep u0_a"
```

**Comment by iptvcld** [comment]
so you would like me to run the above command?

**Comment by iptvcld** [comment]
The problem with the built in andriodTV is that it does the same as this now and where as before it would still show the app_id on idle.  If this is the new norm then i guess i will not know if the tv is displaying the screensaver anymore

**Comment by iptvcld** [comment]
```
adb_response: 101Wake Locks: size=2
Sys2023:dream}

- STREAM_MUSIC:
   Muted: false
   Min: 0
   Max: 15
   Current: 2 (speaker): 3, 4 (headset): 10, 8 (headphone): 10, 80 (bt_a2dp): 10, 400 (hdmi): 6, 1000 (digital_dock): 10, 4000000 (usb_headset): 3, 40000000 (default): 15
   Devices: hdmi
- STREAM_ALARM:
   Muted: false
   Min: 1
   Max: 7
   Current: 2 (speaker): 3, 4 (headset): 5, 8 (headphone): 5, 80 (bt_a2dp): 5, 400 (hdmi): 3, 1000 (digital_dock): 5, 4000000 (usb_headset): 1, 40000000 (default): 7
   Devices: speaker, hdmi
- STREAM_NOTIFICATION:
u0_a75        1204  3320 3776276  60472 0                   0 S com.nvidia.tegrazone3:PersonalGridService
u0_a74        3241  3320 3789968  75748 0                   0 S com.pelmorex.WeatherEyeAndroid.tv
u0_a0         3630  3320 3911496 104408 0                   0 S com.google.android.apps.mediashell
u0_a0         3732  3320 3956580  98760 0                   0 S com.google.android.apps.mediashell:privileged_process0
u0_a1         3894  3320 3811292  39404 0                   0 S com.google.android.tv.remote.service
u0_a28        3913  3320 3821280  89248 0                   0 S com.android.systemui
u0_a10        3965  3320 3945204 114156 0                   0 S com.google.android.gms.persistent
u0_a10        4390  3320 4173848 146788 0                   0 S com.google.android.gms
u0_a105       4442  3320 3749404  33180 0                   0 S com.nvidia.blakepairing
u0_a97        4495  3320 3738320  18088 0                   0 S com.nvidia.shieldtech
u0_a102       4572  3320 3764724  33664 0                   0 S com.nvidia.shield.remote.server
u0_a58        4599  3320 3753268  21096 0                   0 S com.nvidia.osc
u0_a82        4614  3320 3734784  30020 0                   0 S com.nvidia.app.messaging
u0_a18        4664  3320 3750096  33416 0                   0 S com.google.android.leanback.ime
u0_a90        4684  3320 3972768 127264 0                   0 S com.google.android.tvlauncher
u0_a85        4721  3320 3813756  64756 0                   0 S com.google.android.tvrecommendations
u0_a32        5017  3320 3759640  33544 0                   0 S com.android.providers.tv
u0_a34        5557  3320 3747432  27968 0                   0 S com.nvidia.shield.ask
u0_a65        7924  3320 3777924  44400 0                   0 S de.cyberdream.androidtv.notifications.google
u0_a17        8902  3321 1839012  10704 0                   0 S com.google.android.katniss:interactor
u0_a17       11052  3321 1879908  23916 0                   0 S com.google.android.katniss:search
u0_a55       12229  3321 1687196 106188 0                   0 S com.netflix.ninja
u0_a10       12260  3320 3747076  53308 0                   0 S com.google.process.gservices
u0_a122      12917  3320 4651476 234812 0                   0 S ar.tvplayer.tv
u0_a123      13828  3320 3731364  63620 0                   0 S org.xbmc.kodi
u0_a36       22023  3320 3841932 196120 0                   0 S com.google.android.backdrop
u0_a31       23526  3321 1170352  67180 0                   0 S com.android.vending
u0_a3        24984  3320 3729788  67444 0                   0 S com.android.providers.calendar
u0_a29       25014  3320 3744108  75908 0                   0 S com.google.android.tv
u0_a35       25943  3320 3736764  69160 0                   0 S com.android.inputmethod.latin
u0_a61       26878  3320 4418204 100484 0                   0 S com.plexapp.android
u0_a62       28199  3320 3731228  37016 0                   0 S com.plexapp.mediaserver.smb
u0_a75       29445  3320 3757512  53996 0                   0 S com.nvidia.tegrazone3:telemetry
friendly_name: Family Room TV
supported_features: 23997
icon: mdi:television-classic
```

**Comment by JeffLIrion** [comment]
Thanks.  Can you post the output from this one:

```yaml
entity_id: media_player.family_room_tv
command: "dumpsys window windows | grep mCurrentFocus"
```

**Comment by iptvcld** [comment]
THANK YOU!

```
adb_response: mCurrentFocus=Window{bd5abae u0 Sys2023:dream}
friendly_name: Family Room TV
supported_features: 23997
icon: mdi:television-classic
```

**Comment by JeffLIrion** [comment]
For reference, here's the output I got from the above command on a Fire TV stick:

```
adb_response: mCurrentFocus=Window{22af1f52 u0 com.amazon.tv.launcher/com.amazon.tv.launcher.ui.HomeActivity_vNext}
```

And to help me figure out what's going on, here is the shell command that gets the current app:

```
CURRENT_APP=$(dumpsys window windows | grep mCurrentFocus) && CURRENT_APP=${CURRENT_APP#*{* * } && CURRENT_APP=${CURRENT_APP%%/*}
```

**Comment by JeffLIrion** [comment]
I think the original command I had you try wasn't quite right.  Try this one instead:

```yaml
entity_id: media_player.family_room_tv
command: "(dumpsys power | grep 'Display Power' | grep -q 'state=ON' || dumpsys power | grep -q 'mScreenOn=true') && echo -e '1\\c' && dumpsys power | grep mWakefulness | grep -q Awake && echo -e '1\\c' && (dumpsys audio | grep paused | grep -qv 'Buffer Queue' && echo -e '1\\c' || (dumpsys audio | grep started | grep -qv 'Buffer Queue' && echo '2\\c' || echo '0\\c')) && dumpsys power | grep Locks | grep 'size=' && CURRENT_APP=$(dumpsys window windows | grep mCurrentFocus) && CURRENT_APP=${CURRENT_APP#*{* * } && CURRENT_APP=${CURRENT_APP%%/*} && echo $CURRENT_APP && (dumpsys media_session | grep -A 100 'Sessions Stack' | grep -A 100 $CURRENT_APP | grep -m 1 'state=PlaybackState {' || echo) && dumpsys audio | grep '\\- STREAM_MUSIC:' -A 12 && ps -A | grep u0_a"
```

**Comment by iptvcld** [comment]
when i run the above i get
adb_response: 1
friendly_name: Family Room TV
supported_features: 23997
icon: mdi:television-classic

When i run: command: "dumpsys window windows | grep mCurrentFocus"
i get 
adb_response: mCurrentFocus=Window{e303c39 u0 Sys2023:dream}

**Comment by JeffLIrion** [comment]
The output of that command indicates that the he power is on but the device is not awake, and therefore the HA state is idle. In other words, when the state is idle it means that the screensaver is on display.

**Comment by iptvcld** [comment]
With the older version of the app; the below was showing when in idle.  It was still displaying the app_id

volume_level: 0.4
is_volume_muted: false
app_id: Sys2023:dream}
app_name: Displaying Screensaver
source: hdmi
adb_response: null
friendly_name: Family Room TV
supported_features: 21945
icon: mdi:television-classic

**Comment by iptvcld** [comment]
should i continue to use the old version of the app?  I would like to convert over to the new version but just wished the app_id would still show so that i can filter that out for HA

**Comment by JeffLIrion** [comment]
https://github.com/JeffLIrion/ha-androidtv/blob/605a87b524e7cb1232b3cbf33b7f589dc99bec0a/custom_components/androidtv/androidtv/androidtv.py#L71-L72

Change `lazy=True` to `lazy=False` and that should do the trick.

**Comment by iptvcld** [comment]
Thank you! Appreciate all this; So when any updates are made, will I always need to go back and make that update?  Are you able to make this change globally so i dont need a custom compt?

**Comment by JeffLIrion** [comment]
> Thank you! Appreciate all this; So when any updates are made, will I always need to go back and make that update?  Are you able to make this change globally so i dont need a custom compt?

I'm undecided whether it's the right change to make. Also, there's a better way to do it, but it would take more effort and I'd also want to clean up some of the code in the `python-androidtv` repo. 

So I'm not going to make any changes at this time. But I don't envision any more changes to the HA component, so you shouldn't need to update the custom component.

**Comment by iptvcld** [comment]
Thanks, I was trying to keep my custom comp down when loading HA. So if I could just use the built in androidtv and not a custom comp, would be better. But by doing that I'm not sure I can modify the py file.

I guess I can also just create a template value in ha if none then show Displaying Screensaver

**Comment by iptvcld** [comment]
me again - i am using the built in androidtv and i am starting to see this in my logs 90+ times

Updating androidtv media_player took longer than the scheduled update interval 0:00:10

Failed to execute an ADB command. ADB connection re-establishing attempt in the next update. Error: ERROR: 'FAIL' 0006closed

[SHIELD:8009] Failed to connect to service SHIELD-Android-TV-7f317e4100b34f2fadaee563088df94d._googlecast._tcp.local., retrying in 5.0s

**Comment by JeffLIrion** [comment]
I think it might be number 6 here: https://www.home-assistant.io/integrations/androidtv#adb-troubleshooting

Are you using the Python ADB implementation or the ADB server approach?

**Comment by iptvcld** [comment]
i am using the ADB server and my shield box is connected with Ethernet with a static IP.  Have not seen this until i started using the built in comp.  I have just now installed your custom version and changed the lazy flag to False and so far ok.  Just odd that the built in one is giving issues that i have not seen before while using your custom version

**Comment by JeffLIrion** [comment]
I don't know what the issue could be. The code is effectively identical between the latest custom component and the built-in component. 

I recommend the Python ADB approach over the ADB server approach. It's easier to setup, easier to troubleshoot, and it’s one less moving part.

**Comment by iptvcld** [comment]
I just changed over to the python ADB approach and yes i agree much better less more parts.
But i still see errors once in a while in my logs

Failed to execute an ADB command. ADB connection re-establishing attempt in the next update. Error: Reading from 192.168.2.11:5555 timed out (9.0 seconds)

And the very ODD this; when i use your custom; no errors like this.

**Comment by JeffLIrion** [comment]
> I just changed over to the python ADB approach and yes i agree much better less more parts.
> But i still see errors once in a while in my logs
> 
> Failed to execute an ADB command. ADB connection re-establishing attempt in the next update. Error: Reading from 192.168.2.11:5555 timed out (9.0 seconds)
> 
> And the very ODD this; when i use your custom; no errors like this.

The only explanations I can come up with are:

* Your device is going into deep sleep mode, breaking the ADB connection. Users have reported this problem with the Xiaomi Mi Box. You could try installing a wake lock utility, as described in item 6 of the ADB troubleshooting section that I linked above. 
* It's just a coincidence that the built-in component is getting occasional errors but the custom component is not. They should be the same.

**Comment by JeffLIrion** [comment]
Update on this: if you want it to fetch all the state information it can, even if the device is on standby or off, grab the built-in component and change this line:

https://github.com/home-assistant/core/blob/415213a325df9a6037a9b6bfcde16edf46411407/homeassistant/components/androidtv/media_player.py#L664

Change the function parameters to:

```python
self.aftv.update(self._get_sources, lazy=False)
```

I'm going to close this issue, since this repo is just for testing purposes and is not intended to be used in place of the built-in component.
