### ISSUE TITLE
Error after upgrading to lastest “test” version

### ISSUE THREAD

**Issue by bryeartem** [JeffLIrion/ha-androidtv#8]
System fails config check and fails to setup platform with this error:
`Platform error media_player.androidtv - No module named 'custom_components.androidtv.androidtv.exceptions'
Platform error media_player.androidtv - No module named 'custom_components.androidtv.androidtv.exceptions' `

Even after forced restart and uninstalling custom component the error persists.
HA Core 107.6

**Comment by JeffLIrion** [comment]
It should be fixed now. Can you confirm?

**Comment by bryeartem** [comment]
Yes, all set thank you!
